#!/usr/bin/env bash

tasks="master slave influxi dns"
actions="start stop kill exec run watch log"

dname=$(basename ${0%\-*})

# Create all my clones
#
if [ "${dname}" == "_exec" ]; then
  for task in ${tasks}; do
    ln -sf $(readlink -f $0) $(dirname $0)/${task}
    for action in ${actions}; do
      [ ! -f ${task}-${action} ] && ln -sf $(readlink -f $(dirname $0)/${task}) $(dirname $0)/${task}-${action}
    done
  done
  exit 0
fi

# Handle our action
#
case $0 in
  *-exec)   exec docker exec -it ${dname} bash;;
  *-stop)   exec docker stop ${dname};;
  *-log)    exec docker logs ${dname};;
  *-kill)   exec docker rm -f ${dname};;
  *-watch)  exec docker exec -it ${dname} bash -c 'TERM=xterm && watch --diff \\'systemctl -a \| cut -b1-120 \| grep \\.service \| grep loaded \| grep -v systemd \| sort -k3,3 \\' ';;
  *-run)    $(dirname $0)/${dname}-kill;;
  *)        exit;;
esac

# If the first param is a rev tag, then use is
#
case $1 in
  dev)      rev=-dev; shift;;
  0*)       rev=-$1; shift;;
esac

[ -z "${rev}" ] && rev=-dev

# If there are args, then launch interactive
# otherwise, launch daemon
#        
[ -z "$1" ] && mode=-d
[ -n "$1" ] && mode="-it --rm"
mode=-d

case $dname in
  influx)  docker run --name=${dname} ${mode} \
              -p 198.51.100.1:8083:8083 \
              -p 198.51.100.1:8086:8086 \
              -v /var/log/${dname}:/data \
              -e "FORCE_HOSTNAME=198.51.100.1" \
              -e "ADMIN_USER=root" \
              -e "INFLUXDB_INIT_PWD=mypassword" \
              -e "PRE_CREATE_DB=telegraf" \
              tutum/influxdb:latest${rev} $@
            ;;

  master)   docker run --privileged=true --net=host --name master ${mode} \
              -v /var/lib/mesos-master:/data \
              -e 'MESOS_CLUSTER=RickTest' \
              rickalm/dcos:1.7_aws_master${rev} $@
            ;;

  slave)    docker run --privileged=true --net=host --name slave ${mode} \
              -v /var/lib/mesos-slave:/data \
              -e 'EXHIBITOR_ADDRESS=127.0.0.1' \
              rickalm/dcos:1.7_aws_slave${rev} $@
            ;;

  dns)      docker run --privileged=true --net=host --name dns ${mode} \
              -v /var/lib/mesos-dns:/data \
              -e 'EXHIBITOR_ADDRESS=127.0.0.1' \
              rickalm/dcos:1.7_aws_dns${rev} $@
            ;;

esac

exit

docker exec -it master watch -n 0.2 --diff 'systemctl -a | grep dcos | cut -b1-120 | sort -k3,3 -k1,1'
docker exec -it master /bin/bash

