#!/usr/bin/env bash

dname=${0%\-*}

# Create all my clones
#
for s in start stop kill exec run; do
  [ ! -f ${dname}-${s} ] && ln -s $(readlink -f $0) ${dname}-${s}
done

case $0 in
  *-exec)   exec docker exec -it ${dname} bash;;
  *-stop)   exec docker stop ${dname};;
  *-kill)   exec docker rm -f ${dname};;
  *-exec)   exec docker exec -it ${dname} watch systemctl -a;;

  *-run)    ${dname}-kill
esac

case $0 in
  influx)  docker run -d --name=${dname} \
              -p 198.51.100.1:8083:8083 \
              -p 198.51.100.1:8086:8086 \
              -v /var/log/${dname}:/data \
              -e "FORCE_HOSTNAME=198.51.100.1" \
              -e "ADMIN_USER=root" \
              -e "INFLUXDB_INIT_PWD=mypassword" \
              -e "PRE_CREATE_DB=telegraf" \
              tutum/influxdb:latest
            ;;

