#!/usr/bin/env bash

dname=$(basename ${0%\-*})

# Create all my clones
#
for s in start stop kill exec run; do
  [ ! -f ${dname}-${s} ] && ln -s $(readlink -f $0) ${dname}-${s}
done

# Handle our clone names
#
case $0 in
  *-exec)   exec docker exec -it ${dname} bash;;
  *-stop)   exec docker stop ${dname};;
  *-kill)   exec docker rm -f ${dname};;
  *-exec)   exec docker exec -it ${dname} watch systemctl -a;;
  *-run)    $(dirname $0)/${dname}-kill
esac

# If the first param is a rev tag, then use is
#
case $1 in
  dev)      rev=_dev; shift;;
  0*)       rev=_$1; shift;;
esac

# If there are args, then launch interactive
# otherwise, launch daemon
#        
[ -z "$1" ] && mode=-d
[ -n "$1" ] && mode=-it --rm
mode=-d

case $dname in
  influx)  docker run --name=${dname} ${mode} \
              -p 198.51.100.1:8083:8083 \
              -p 198.51.100.1:8086:8086 \
              -v /var/log/${dname}:/data \
              -e "FORCE_HOSTNAME=198.51.100.1" \
              -e "ADMIN_USER=root" \
              -e "INFLUXDB_INIT_PWD=mypassword" \
              -e "PRE_CREATE_DB=telegraf" \
              tutum/influxdb:latest${rev} $@
            ;;

  master)   docker run --privileged=true --net=host --name master ${mode} \
              -v /var/lib/mesos-master:/data \
              -e 'MESOS_CLUSTER=RickTest' \
              rickalm/dcos:1.7_aws_master${rev} $@
            ;;
esac

exit

docker exec -it master watch -n 0.2 --diff 'systemctl -a | grep dcos | cut -b1-120 | sort -k3,3 -k1,1'
docker exec -it master /bin/bash

